---
- hosts: localhost
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: '{{ azure_resource_group }}'
        location: eastus
      register: rg
    - debug:
        var: rg
