---
- hosts: localhost
  tasks:
    - name: Create vm group
      azure_rm_virtualmachine:
        resource_group: '{{rez_group}}'
        name: '{{vm_name}}'
        vm_size: '{{vm_size}}'
        admin_username: chouseknecht
        ssh_password: 'MikeTest123'
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
